name: GitHub Pages

on:
  repository_dispatch:
    types: [sync]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      FROM_REPO_USER: 'hgshdt'
      FROM_REPO_NAME: 'portfolio'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.FROM_REPO_USER }}/${{ env.FROM_REPO_NAME }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: master
          path: ./From
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        working-directory: ./From
        run: npm install
      - name: Build
        working-directory: ./From
        run: |
          npm run build
          touch dist/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          publish_dir: ./From/dist
